### ISSUE TITLE
Releases would be nice

### ISSUE THREAD

**Issue by DanielJonesEB** [pivotal-k8s/kind-on-c#10]
Hi folks,

We're using kindonc to test a Kubernetes-based Concourse training environment. We're tracking master of this repo currently, and it'd be nice to be able to track tested releases instead.

Any chance of changing the pipeline to tag releases, so we can track those instead? Tagging images with versions that correspond to the source code tags would also be lovely.

**Comment by hoegaarden** [comment]
> We're tracking master of this repo currently, and it'd be nice to be able to track tested releases instead.

When changes are made to kind-on-c, they go into the `dev` branch, and are merged into `master` only if the whole pipeline succeeded. This is also true for updates of the base-image. And the image is referenced by the sha256 digest [in the task's config][tc], to ensure the task will only ever use a tested image.

When you track the tip of master, you should always get things that have made it completely through the pipeline, that includes a specific version of the container image.

I wouldn't know what else to test specifically for a release.

I think I didn't introduce any breaking changes yet (?) and had the plan to continue without specific releases until this is not true anymore.

> Any chance of changing the pipeline to tag releases, so we can track those instead? Tagging images with versions that correspond to the source code tags would also be lovely.

I assume this request doesn't come out of the blue. If possible I'd like to understand what broke for you.

I am not against releases, however as it stands right now, I am not sure which benefits they'd provide. 

[tc]: https://github.com/pivotal-k8s/kind-on-c/blob/21d5ddddb54af0bc3f6d53e93494ea79aeea85c0/kind.yaml#L7

**Comment by DanielJonesEB** [comment]
'ello! We didn't experience a breakage, so that's good! I also didn't realise about the fact that everything goes through another branch first. So sounds like there's probably no need for releases here.

**Comment by hoegaarden** [comment]
Thanks for the feedback.
I created #11 to create some docs about how the thing is tested.
